version: 2

models:
  - name: repayments_clean
    description: "Cleaned repayments for analysis"
    tests:
      - not_null:
          column_name: loan_id
      - not_null:
          column_name: amount_trans
      - relationships:
          column_name: loan_id
          to: ref('landing_customers')
          field: loan_id
