version: 2

snapshots:
  - name: loan_metrics_snapshot
    description: "Snapshot of loan metrics (total repaid and last payment) to track loan state over time"
    tests:
      - not_null:
          column_name: loan_id
      - unique:
          column_name: loan_id
      - not_null:
          column_name: total_repaid
